import pandas as pd

def build_features(df: pd.DataFrame, kpi: str) -> pd.DataFrame:
    """
    Builds temporal features: lag_1, lag_7, rolling_mean_7, rolling_std_7.
    Handles NaN values generated by lags and rolling windows by filling or dropping.
    """
    feature_df = df.copy()
    
    # Ensure chronologically sorted
    feature_df = feature_df.sort_values("date").reset_index(drop=True)
    
    # Generate lags
    feature_df[f"{kpi}_lag_1"] = feature_df[kpi].shift(1)
    feature_df[f"{kpi}_lag_7"] = feature_df[kpi].shift(7)
    
    # Generate rolling statistics
    feature_df[f"{kpi}_roll_mean_7"] = feature_df[kpi].rolling(window=7, min_periods=1).mean()
    feature_df[f"{kpi}_roll_std_7"] = feature_df[kpi].rolling(window=7, min_periods=1).std()
    
    # Fill remaining NaNs (std can be NaN if window has 1 element)
    feature_df = feature_df.bfill()  # backfill early NaNs from lag and rolling std
    
    # If any still remain (e.g. whole column is NaN), fill with 0
    feature_df = feature_df.fillna(0)
    
    return feature_df
